"""
OmniVoice — Interactive .env configurator
Run: python setup_env.py
"""
import os
import sys

# ── ANSI ─────────────────────────────────────────────────────────────────────
GREEN  = "\033[92m"
YELLOW = "\033[93m"
BLUE   = "\033[94m"
DIM    = "\033[2m"
BOLD   = "\033[1m"
RESET  = "\033[0m"

ENV_FILE = ".env"


def info(msg):  print(f"  {GREEN}✓{RESET}  {msg}")
def warn(msg):  print(f"  {YELLOW}⚠{RESET}  {msg}")
def section(title): print(f"\n{BOLD}{BLUE}── {title} ──────────────────────────────{RESET}\n")


def ask(prompt, default="", secret=False):
    hint = f" [{default}]" if default else ""
    try:
        if secret:
            import getpass
            val = getpass.getpass(f"  {prompt}{hint}: ").strip()
        else:
            val = input(f"  {prompt}{hint}: ").strip()
    except (KeyboardInterrupt, EOFError):
        print("\n  Cancelled.")
        sys.exit(0)
    return val or default


def choose(prompt, choices, default=None):
    opts = " / ".join(
        f"{YELLOW}{c}{RESET}" if c == default else c for c in choices
    )
    default_str = f" [{default}]" if default else ""
    while True:
        try:
            val = input(f"  {prompt} ({opts}){default_str}: ").strip().lower()
        except (KeyboardInterrupt, EOFError):
            print("\n  Cancelled.")
            sys.exit(0)
        if not val and default:
            return default
        if val in choices:
            return val
        print(f"  {YELLOW}Please choose one of: {', '.join(choices)}{RESET}")


def write_env(values: dict):
    # Load existing .env if present
    existing = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    existing[k.strip()] = v.strip()

    existing.update({k: v for k, v in values.items() if v})

    with open(ENV_FILE, "w") as f:
        f.write("# OmniVoice configuration — generated by setup_env.py\n\n")
        for k, v in existing.items():
            f.write(f"{k}={v}\n")

    info(f".env updated  →  {ENV_FILE}")


def main():
    print(f"""
{BOLD}{GREEN}  OmniVoice — Setup Wizard{RESET}
  {DIM}Configure your voice AI pipeline. Press Enter to keep defaults.{RESET}
""")

    cfg = {}

    # ── LLM ──────────────────────────────────────────────────────────────────
    section("LLM — which AI brain?")
    print(f"  {DIM}anthropic → Claude  |  openai → GPT-4o  |  ollama → local, free  |  openrouter → 100+ models{RESET}\n")

    llm = choose("Provider", ["anthropic", "openai", "ollama", "openrouter"], default="anthropic")
    cfg["LLM_PROVIDER"] = llm

    if llm == "anthropic":
        cfg["ANTHROPIC_API_KEY"] = ask("Anthropic API key (console.anthropic.com)", secret=True)
        cfg["ANTHROPIC_MODEL"]   = ask("Model", default="claude-3-5-sonnet-20241022")

    elif llm == "openai":
        cfg["OPENAI_API_KEY"] = ask("OpenAI API key (platform.openai.com)", secret=True)
        cfg["OPENAI_MODEL"]   = ask("Model", default="gpt-4o")

    elif llm == "ollama":
        print(f"  {DIM}Make sure Ollama is running: ollama serve{RESET}")
        cfg["OLLAMA_MODEL"]    = ask("Model", default="llama3")
        cfg["OLLAMA_BASE_URL"] = ask("Ollama URL", default="http://localhost:11434")

    elif llm == "openrouter":
        cfg["OPENROUTER_API_KEY"] = ask("OpenRouter API key (openrouter.ai)", secret=True)
        cfg["OPENROUTER_MODEL"]   = ask("Model", default="anthropic/claude-3.5-sonnet")

    cfg["SYSTEM_PROMPT"] = ask(
        "System prompt",
        default="You are a helpful voice assistant. Keep responses concise and conversational."
    )

    # ── ASR ──────────────────────────────────────────────────────────────────
    section("ASR — speech to text")
    print(f"  {DIM}whisper → local, free, no key  |  deepgram → cloud, fast, free tier at console.deepgram.com{RESET}\n")

    asr = choose("Provider", ["whisper", "deepgram"], default="whisper")
    cfg["ASR_PROVIDER"] = asr

    if asr == "whisper":
        print(f"  {DIM}Model sizes: tiny (fastest) → base → small (best accuracy){RESET}")
        cfg["WHISPER_MODEL_SIZE"] = choose("Model size", ["tiny", "base", "small"], default="base")
    elif asr == "deepgram":
        cfg["DEEPGRAM_API_KEY"] = ask("Deepgram API key", secret=True)

    # ── TTS ──────────────────────────────────────────────────────────────────
    section("TTS — text to speech")
    print(f"  {DIM}edge → free, no key (Microsoft neural)  |  elevenlabs → paid, best quality  |  openai → paid{RESET}\n")

    tts = choose("Provider", ["edge", "elevenlabs", "openai"], default="edge")
    cfg["TTS_PROVIDER"] = tts

    if tts == "edge":
        cfg["EDGE_TTS_VOICE"] = ask("Voice", default="en-US-AriaNeural")
    elif tts == "elevenlabs":
        cfg["ELEVENLABS_API_KEY"] = ask("ElevenLabs API key", secret=True)
        cfg["ELEVENLABS_VOICE_ID"] = ask("Voice ID", default="EXAVITQu4vr4xnSDxMaL")
    elif tts == "openai":
        cfg["OPENAI_TTS_VOICE"] = ask("Voice", default="alloy")

    # ── Twilio / WhatsApp ─────────────────────────────────────────────────────
    section("WhatsApp (optional — skip if using CLI only)")
    setup_wa = choose("Set up WhatsApp?", ["yes", "no"], default="no")

    if setup_wa == "yes":
        cfg["TWILIO_ACCOUNT_SID"]    = ask("Twilio Account SID (console.twilio.com)")
        cfg["TWILIO_AUTH_TOKEN"]     = ask("Twilio Auth Token", secret=True)
        cfg["TWILIO_WHATSAPP_FROM"]  = ask("WhatsApp number", default="whatsapp:+14155238886")
        cfg["TUNNEL_PROVIDER"]       = choose("Tunnel", ["cloudflared", "ngrok"], default="cloudflared")
        if cfg["TUNNEL_PROVIDER"] == "ngrok":
            cfg["NGROK_AUTH_TOKEN"]  = ask("ngrok auth token (optional)", secret=True)

    # ── Write ─────────────────────────────────────────────────────────────────
    write_env(cfg)

    print(f"""
{GREEN}  All set!{RESET}

  {BOLD}Terminal voice chat:{RESET}
    python -m omni_voice.voice_cli

  {BOLD}WhatsApp server:{RESET}
    python start.py
""")


if __name__ == "__main__":
    main()
